server:
  port: 9090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cards
    username: postgres
    password: 1234567890a
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect