server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accounts
    username: postgres
    password: 1234567890a
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
